//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterArs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportView
    {
        public string IATA_Code { get; set; }
        public string Local_Code { get; set; }
        public string Airport { get; set; }
    }
}
